services:
  - type: web
    name: prince-ai-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

    envVars:
      - key: NODE_VERSION
        value: 20
